### ISSUE TITLE
addDoc for duplicate documents

### ISSUE THREAD

**Issue by ittaboba** [decisively/wink-bm25-text-search#20]
I have seen that if I try to add a document with an existing id, it throws this error
```
if ( documents[ id ] !== undefined ) {
  throw Error( 'winkBM25S: Duplicate document encountered: ' + JSON.stringify( id ) );
}
```
I need to handle document updates. I am wondering if it's possible to update the model if I know both the original and updated versions of a document.

Thank you!

**Comment by sanjayaksaxena** [comment]
Hi @ittaboba 

Not able to spot any drawbacks.

Best,
Sanjaya
