### ISSUE TITLE
How to run this application?

### ISSUE THREAD

**Issue by passionate2023** [decisively/wink-bm25-text-search#23]
Hi,

I tried to run this application but just noticed only command in readme. 
also, i have collection of text document. is text document is supported or any tool to convert text to json files
where to place the json or text files and load it? just placing the files in a folder would be sufficient

Thanks

**Comment by sanjayaksaxena** [comment]
Hi @passionate2023 

Please follow this link: https://winkjs.org/showcase-bm25-text-search/ — it is a working example with a github link containing the code.

Best,
Sanjaya
