### ISSUE TITLE
Trying to use this in a TypeScript project: Cannot call a namespace ("winkBM25")

### ISSUE THREAD

**Issue by Chaddeus** [decisively/wink-bm25-text-search#24]
Here' how I'm attempting to use this. And here's the interesting thing, it works great when in dev mode (npm run dev). But it fails to build properly (npm run build).

**I get the error:** Cannot call a namespace ("winkBM25")

```
import winkNLP from 'wink-nlp'
import winkModel from 'wink-eng-lite-web-model'
import * as winkBM25 from 'wink-bm25-text-search'

export function createEmbeddings(chunks: string[]): void {
    engine = winkBM25() // <--------------- This is where the error is occurring.
    engine.defineConfig({ fldWeights: { text: 1 } })
    engine.definePrepTasks( [ prepTask ] )

    const uniqueChunks = [...new Set(chunks)] // make sure unique
    uniqueChunks.forEach((text, index) => engine.addDoc({ text }, index))
    engine.consolidate() // consolidate the learnings
}
```

Is there a different way to initialize the engine that is TypeScript friendly?

**Comment by rachnachakraborty** [comment]
Hello @Chaddeus 

Thanks for sharing the issue.

As of now we have not added TypeScript support on `wink-bm25-text-search` package.

Would be wonderful if you can consider contributing.

Best,
Rachna

**Comment by rachnachakraborty** [comment]
If its of some help, TypeScript support on [BM25 Vectorizer](https://winkjs.org/wink-nlp/bm25-vectorizer.html) is integrated with [wink-nlp](https://github.com/winkjs/wink-nlp).  

Several similarity methods – Cosine, Tversky, Sørensen-Dice, Otsuka-Ochiai are also available.

**Comment by Chaddeus** [comment]
Thank you!

I actually managed to get it to work. I changed my import to this:

```
import winkBM25fIMS from 'wink-bm25-text-search'
```

Thank you for the great product!
